---
language: go
go:
- '1.3'
sudo: false
env:
  global:
  - PATH=$HOME/gopath/bin:$HOME/.local/bin:$PATH
  - DATABASE_URL=postgres://postgres@localhost:5432/travis
addons:
  postgresql: '9.3'
before_install:
- go get github.com/tools/godep
- go get code.google.com/p/go.tools/cmd/cover
- godep restore
- go install -a -race std
- mkdir -p $HOME/.local/bin
- pip install --user flake8
before_script:
- createdb -U postgres travis
after_success:
- go get github.com/mitchellh/gox
- make crosstars
deploy:
  provider: releases
  api_key:
    secure: yYVIN8+dw6cIPCesQsSpyKgEHVQ+xBqluM7ydUIlmV5wyWVLms8d+9Dc+J4PbC9EyzwiTSXdxnYwwJbaiPt9fprnX83d8FE/P+JaXqvffBXdy2UUATuS+KzM9Hp+qo7l0LMJfnadNQ40E/Z3gr8pcU4WOWo33D8ss3XbG3iZbrw=
  file:
  - tory-darwin-amd64.tar.bz2
  - tory-linux-amd64.tar.bz2
  - tory-windows-amd64.tar.bz2
  - SHA256SUMS
  on:
    repo: modcloth/tory
    all_branches: true
    tags: true
notifications:
  email: github+tory@modcloth.com
