---
language: go
go:
- '1.3'
sudo: false
env:
  global:
  - PATH=$HOME/gopath/bin:$PATH
before_script:
- go get github.com/tools/godep
- go get code.google.com/p/go.tools/cmd/cover
- godep restore
- go install -a -race std
notifications:
  email: github+tory@modcloth.com
