---
language: go
go:
- '1.3'
sudo: false
env:
  global:
  - PATH=$HOME/gopath/bin:$HOME/.local/bin:$PATH
  - DATABASE_URL=postgres://postgres@localhost:5432/travis
addons:
  postgresql: '9.3'
  artifacts:
    key:
      secure: ce0uEeu7AG2I6CQkreCXjeDzL451IBvnuVyEiOX5811ZZ85KlniOP9X06dQek3jrAkyS5z383Vs10bz8Wzam3WxVC565vs0Wuiuu/NE+KUecdnffD77ekrJr9T8lyGJIGJeSoGCbD31MWQfEzZoMna2/lJ8dq1b+cCD+nqRso9s=
    secret:
      secure: Ub6hECj5J9aUv/6nnSutkrz32TnAvFe9DuDX0sitOPrmfEf9A3mF/3xent2PwnkRapUfTtu2QF+/EnI+cr33aO0UQ+hOMV/mHFEOBsJZzLMrmr1X9LB6ful0uk/yQX1Ki71XN6YosC7okqcf+LJjRjAe3Mv/EoO3BH4kDtWwUvg=
    bucket: modcloth-public-travis-artifacts
before_install:
- go get github.com/tools/godep
- go get code.google.com/p/go.tools/cmd/cover
- godep restore
- go install -a -race std
- mkdir -p $HOME/.local/bin
- pip install --user flake8
before_script:
- createdb -U postgres travis
after_success:
- go get github.com/mitchellh/gox
- make crosstars
notifications:
  email: github+tory@modcloth.com
