---
language: go
go:
- '1.3'
sudo: false
env:
  global:
  - PATH=$HOME/gopath/bin:$PATH
  - DATABASE_URL=postgres://postgres@localhost:5432/travis
addons:
  postgresql: '9.3'
before_install:
- go get github.com/tools/godep
- go get code.google.com/p/go.tools/cmd/cover
- godep restore
- go install -a -race std
before_script:
- createdb -U postgres travis
after_success:
- go get github.com/mitchellh/gox
- make crossbuild
deploy:
  provider: releases
  api_key:
    secure: yYVIN8+dw6cIPCesQsSpyKgEHVQ+xBqluM7ydUIlmV5wyWVLms8d+9Dc+J4PbC9EyzwiTSXdxnYwwJbaiPt9fprnX83d8FE/P+JaXqvffBXdy2UUATuS+KzM9Hp+qo7l0LMJfnadNQ40E/Z3gr8pcU4WOWo33D8ss3XbG3iZbrw=
  file:
  - build/darwin/amd64/tory
  - build/darwin/amd64/tory-ansible-inventory
  - build/darwin/amd64/tory-sync-from-joyent
  - build/linux/amd64/tory
  - build/linux/amd64/tory-ansible-inventory
  - build/linux/amd64/tory-sync-from-joyent
  - build/windows/amd64/tory-ansible-inventory.exe
  - build/windows/amd64/tory-sync-from-joyent.exe
  - build/windows/amd64/tory.exe
  on:
    repo: modcloth/tory
    all_branches: true
    tags: true
notifications:
  email: github+tory@modcloth.com
